### ISSUE TITLE
Can't generate unit test report

### ISSUE THREAD

**Issue by skal111** [mdasberg/grunt-karma-sonar#12]
Hi

Thanks for your karma-sonar-plugin which I managed to get working perfectly for coverage report. Unfortunately I can't get my unit tests report to get analysed by sonar.

Regarding unit tests my karma.conf.js file defines the following
junitReporter: 
{
		outputFile: 'target/karma-reports/angular-test-results.xml'
}

my gruntfile.js karma_sonar section is
sources : 
                [{
                    path : 'src/main/webapp/js',
                    coverageReport : 'target/js-code-coverage/lcov-only.txt',
                    testReport : 'target/karma-reports/angular-test-results.xml'
                }],

When karma_sonar runs I can find a .tmp/sonar/TESTS-xunit.xml file which is the exact copy of my karma generated test report. But then, when sonar executes, this file doesn't seem to be taken into account. I only get the coverage report as you can see on the attached screenshot.

Am I doing something wrong or is there a bug?
![capture1](https://cloud.githubusercontent.com/assets/9783772/5635187/27cfec0e-95e7-11e4-8695-a38243b77c4a.jpg)

**Comment by mdasberg** [comment]
I have been able to reproduce the problem. When using nested describes, the karma junit-reporter creates testcases with multiple classnames which isn't allowed anymore by the sonar plugin.

for example:

```js
describe('x',function() {
    it('should do something with x', function() {}
    describe('y', function() {
            it('should do something with y', function() {}
    }
}
```

karma will generate a report like this:

```xml
<testsuite name="SomeTest" errors="0" failures="0" tests="2" time="....">
    <testcase name="should do something with x" time="..." classname="x"/>
    <testcase name="should do something with y" time="..." classname="x y"/>
</testsuite>
```

Since sonar 4.3 it is not allowed to put this in the same file.
I am trying to find a solution to rewrite the classname based on the test file name, so sonar will accept the tests again.

**Comment by skal111** [comment]
I have a few nested describe indeed but I'm using Sonar 3.7.4. I haven't tried the karma-sonar-plugin with other versions of sonar. I'll send you a copy of my test-resuts.xml file in a separate email.

Thank you.

**Comment by skal111** [comment]
Hello

As replied on github here is my karma junit generated test results file should you need it to reproduce my issue.

Thanks

Date: Fri, 9 Jan 2015 11:08:48 -0800

**Comment by andyflatt** [comment]
How did you resolve this issue? I am seeing the same thing I think.  When I look in .tmp/sonar/result/TEST.xunit.xml it is empty
