### ISSUE TITLE
'karma_sonar' task doesn't stop when errors occur.

### ISSUE THREAD

**Issue by MrHus** [mdasberg/grunt-karma-sonar#13]
Task doesn't stop when errors occur.

For example:

When sonar-runner is not installed you get the following error:

```
The following error occured while trying to upload to sonar: Error: Error: not found: sonar-runner
```

However this doesn't stop the task from running, ideally it would stop running after the error code.

Another example is when something goes wrong when uploading to sonar:

```
The following error occured while trying to upload to sonar: Error
```

Basically whenever an error occurs the task should stop grunt.

**Comment by mdasberg** [comment]
Just released a new version 0.2.0 which should fix this.
