### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by grahamcrackers** [mdasberg/grunt-karma-sonar#17]
Hi,

I'm getting this error when I try to run grunt karma_sonar
```
Loading "sonar.js" tasks...ERROR
>> Error: Cannot find module 'fs-extra'
Warning: Task "karma_sonar" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by mdasberg** [comment]
Just release a new version 0.2.2. It should be fixed now

**Comment by grahamcrackers** [comment]
Thanks! I've already tried it out and it seems to be working.

I'm sure you intended to update your grunt command so you also may want to update your README from 
```
grunt.initConfig({
  karma_sonar: {...
```
to
```
grunt.initConfig({
  karmaSonar: {...
```
