### ISSUE TITLE
Karma sonar should not write options instance when they are undefined.

### ISSUE THREAD

**Issue by MrHus** [mdasberg/grunt-karma-sonar#22]
The sonar-runner has the option of defining a global configuration. This way you can have multiple projects that can use the same configuration. So you don't have to set the hostname and authentication data of sonar per project, as a bonus you don't have to commit them into git.

See: http://docs.sonarqube.org/display/SONAR/Installing+and+Configuring+SonarQube+Runner

This will only work when you don't add arguments to sonar-runner because adding them overwrites the global configuration. So if you send -Dsonar.host.url= you overwrite the globally configured one.

Currently the grunt-karma-sonar runner does exactly that it always overrides the following with default values:

```javascript
'-Dsonar.host.url=' + sonarOptions.instance.hostUrl,
'-Dsonar.jdbc.url=' + sonarOptions.instance.jdbcUrl,
'-Dsonar.jdbc.username=' + sonarOptions.instance.jdbcUsername,
'-Dsonar.jdbc.password=' + sonarOptions.instance.jdbcPassword,
'-Dsonar.login=' + sonarOptions.instance.login,
'-Dsonar.password=' + sonarOptions.instance.password
```

These are there defaults:

```javascript
instance: {
    hostUrl: 'http://localhost:9000',
    jdbcUrl: 'jdbc:h2:tcp://localhost:9092/sonar',
    jdbcUsername: 'sonar',
    jdbcPassword: 'sonar',
    login: 'admin',
    password: 'admin'
}
```

A previous version of grunt-karma-sonar had this check:

```javascript
if (options.instance !== undefined) {
    args.push('-Dsonar.host.url=' + options.instance.hostUrl);
    args.push('-Dsonar.jdbc.url=' + options.instance.jdbcUrl);
    if (options.instance.jdbcUsername !== undefined) {
        args.push('-Dsonar.jdbc.username=' + options.instance.jdbcUsername);
    }
    if (options.instance.jdbcPassword !== undefined) {
        args.push('-Dsonar.jdbc.password=' + options.instance.jdbcPassword);
    }
    if (options.instance.profile !== undefined) {
        args.push('-Dsonar.profile=' + options.instance.profile);
    }
    args.push('-Dsonar.login=' + options.instance.login);
    args.push('-Dsonar.password=' + options.instance.password);
}
return args;
```

This prevented the writing of the -D options for the runner when the options instance was left empty.
Which is exactly what you want to do when you want to use the global configuration.

I would like to see the options.instance undefined check to return. So that when it is undefined it doesn't send the -D arguments to sonar runner. This way a nice feature (which I depend on ;P) would return.

**Comment by mdasberg** [comment]
Fixed was released in version 0.2.4.
