### ISSUE TITLE
Cannot install behind (corporate) proxy

### ISSUE THREAD

**Issue by AdamSelene** [mdasberg/grunt-karma-sonar#25]
Hi,
The npm install phase seems to fail when behind a corporate proxy (npm itself is configured properly, and both http_proxy and https_proxy environment variables are set) when trying to fetch sonar-runner:
```
Using remote location to fetch sonar-runner.
Could not download the latest version of sonar-runner from the remote repository due to the following error [Error: getaddrinfo ENOTFOUND repository.sonatype.org].
```
Maybe use something like https://www.npmjs.com/package/global-tunnel?
Thanks!

**Comment by mdasberg** [comment]
you can configure the following:

See: https://github.com/mdasberg/grunt-karma-sonar#deciding-where-to-get-sonar-runner-from
