### ISSUE TITLE
Fatal:Error while using it with Grunt

### ISSUE THREAD

**Issue by joshijimit** [mdasberg/grunt-karma-sonar#28]
I am getting below error while using it with my grunt build. Any suggestions? Any logs through which I can dig further?

Fatal error: spawn D:\Projects\In-House\Eclipse-Workspace\AngularDemo\node_modul
es\grunt-karma-sonar\lib\sonar-runner-2.4\bin\sonar-runner ENOENT

My config is as below,
karmaSonar: {
         options: {            
            instance: {
                 hostUrl : 'http://localhost:9000',
                 jdbcUrl : 'jdbc:mysql://localhost:3306/sonar',
                 login: 'root',
                 password: 'password'
            }
		},
		sonar_export: {
			project: {
			  key: 'angular-demo',
			  name: 'Angular Demo',
			  version: '1.0.0'
			},
			paths: [
				{
				  cwd: 'src', // the current working directory'
				  src: [ 'src/**/*.js', '!src/**/*.spec.js', '!src/assets/**/*.js' ], // the source directory within the cwd
				  test: ['!src/**/*.js', 'src/**/*.spec.js', '!src/assets/**/*.js'], // the test directory within the cwd
				  reports: {
					  unit: 'TESTS-Firefox_40.0.0_(Windows_8.1_0.0.0).xml', // the result file within the cwd
					  coverage: 'build/coverage/Firefox 40.0.0 (Windows 8.1 0.0.0)/lcov.info', // the glob for lcov files'
					  itCoverage: 'build/coverage/Firefox 40.0.0 (Windows 8.1 0.0.0)/lcov.info' // the glob for integration lcov files'
				  }
				}
			]
	    }
	}

**Comment by mdasberg** [comment]
Can you run the grunt process with --verbose?

**Comment by mdasberg** [comment]
is this still an issue? otherwise I'd like to close it
