### ISSUE TITLE
karma-junit-reporter 0.3.4 requirement not explicit

### ISSUE THREAD

**Issue by mkulke** [mdasberg/grunt-karma-sonar#30]
hi there,

i think compatibility w/ karma-junit-reporter 0.2.x was broken with v0.2.14. that would be a breaking change, no? if keeping 0.2.x karma-junit-reporter backwards-compatibility is not worth it, maybe a hard dependency in package.json would be sufficient?

cheers,

magnus

**Comment by mdasberg** [comment]
I added some tests that process a karma-junit-reporter 0.2.2 generated report and it gets processed.
@see https://travis-ci.org/mdasberg/grunt-karma-sonar/builds/79697577

could you show your configuration? and log?
