### ISSUE TITLE
File merge fails if there is disabled jasmine test ('xit()')

### ISSUE THREAD

**Issue by bvm1178** [mdasberg/grunt-karma-sonar#32]
Sonar analysis failed with 'Warning: Cannot call method 'replace' of undefined' message when there is disabled test in test code i.e. it('blah-blah') is prefixed with 'x' we have xit('blah-blah'). 
Such tests are marked as disabled in junit report and caused the failure on remove escaped characters step.

**Comment by mdasberg** [comment]
fixed in version 0.2.16 (both xit and it are supported)
