### ISSUE TITLE
Error when running in a directory with a whitespace.

### ISSUE THREAD

**Issue by spotlerbob** [mdasberg/grunt-karma-sonar#40]
When i'm running grunt karma sonar in a directory with a whitespace in it, I get the following output.

> Running "karmaSonar:cmsSonar" (karmaSonar) task
> \>\> No jUnit report has been specified
> \>\> No integration jUnit report has been specified
> \>\> No integration coverage report has been specified
> Error: Could not find or load main class test.node_modules.grunt-karma-sonar.lib.sonar-runner-2.4.lib.sonar-runner-dist-2.4.jar
> Warning: The following error occured while trying to upload to sonar: Error Use --force to continue.

The problem seems to be on line 200 of sonar.js:

```javascript
var libDir = path.join(__dirname, '..', 'lib');
if (grunt.file.exists(libDir)) {
  glob.sync('**/bin/sonar-runner', {cwd: libDir, root: '/'}).forEach(function (file) {
   opts.cmd = libDir + path.sep + file;
  });
}
```

The libDir should be surrounded with '.

**Comment by mdasberg** [comment]
Thanks for reporting this. 
I will have a look at it.

**Comment by mdasberg** [comment]
I managed to reproduce this on osx as well. The path is escaped correctly and the sonar-runner is executed. This seems to be an old issue with sonar. 

See: http://osdir.com/ml/java-sonar-general/2012-06/msg00655.html

There are 2 simple solutions for this problem:
- make sonar-runner available on your path (which won't use the one in the path with spaces)
- don't use a whitespace in the directory structure.
