### ISSUE TITLE
sonar-runner: not found

### ISSUE THREAD

**Issue by tristobal** [mdasberg/grunt-karma-sonar#44]
Hi there

When i try to configure some remote location for the download of sonar-runner, the installation script log shows "sonar-runner: not found".

    $ npm install grunt-karma-sonar --sonarrunner_cdnurl=http://200.14.166.249:5680/node_dependencies/

    > grunt-karma-sonar@0.2.18 install /home/csanchez/deleteme/node_modules/grunt-karma-sonar
    > node install.js

    /bin/sh: 1: sonar-runner: not found
    /home/csanchez/deleteme
    └─┬ grunt-karma-sonar@0.2.18 
      ├── async@1.5.2 
      ├─┬ glob@6.0.4 
      │ └── minimatch@3.0.0 
      └── lodash@3.10.1 
    
    npm WARN ENOENT ENOENT: no such file or directory, open '/home/csanchez/deleteme/package.json'
    npm WARN EPACKAGEJSON deleteme No description
    npm WARN EPACKAGEJSON deleteme No repository field.
    npm WARN EPACKAGEJSON deleteme No README data
    npm WARN EPACKAGEJSON deleteme No license field.

But the file (sonar-runner) exists in the folder

    ~/deleteme/node_modules/grunt-karma-sonar$ tree
    .
    ├── CHANGELOG.md
    ├── Gruntfile.js
    ├── install.js
    ├── lib
    │   └── sonar-runner-2.4
    │       ├── bin
    │       │   ├── sonar-runner
    │       │   └── sonar-runner.bat
    │       ├── conf
    │       │   └── sonar-runner.properties
    │       └── lib
    │           └── sonar-runner-dist-2.4.jar
    ├── LICENSE-MIT

It is a normal behaviour?

PS: In my CDN URL I rename "sonar-runner-dist-2.4.zip" to "sonar-runner-dist.zip"

**Comment by mdasberg** [comment]
Looks like you don't have a package.json file in your folder. (try running npm init -y)
Your tree looks ok, it extracted the dist in the lib folder.

I will add some extra logging to the install script for the next release

**Comment by tristobal** [comment]
Yes i don't have package.json, i install grunt-karma-sonar in a new folder for example purpose. But, you don't response my question, is it normal the log message? "sonar-runner: not found"?

**Comment by tristobal** [comment]
Yes i don't have package.json, i install grunt-karma-sonar in a new folder for example purpose. But, you don't response my question, is it normal the log message? "sonar-runner: not found"?

PS: Sorry for close and reopen issue, i have poor shooting =P

**Comment by mdasberg** [comment]
Yes, atm the npm install task checks if sonar-runner is globally available. If it is not it will show this message and continue to get it from the cdnurl or cdndir.

In the next release I will:
- make sure it checks both globally and in the lib dir (in case of an npm update)
- update the message to indicate it did not find sonar-runner globally

**Comment by mdasberg** [comment]
@tristobal, I just release version [0.2.19](https://github.com/mdasberg/grunt-karma-sonar/releases/tag/0.2.19) which checks if sonar is available globally (command-line) as well as locally (lib directory) and should give a better information message.

**Comment by tristobal** [comment]
Great improvement!
